http:
  routers:
    fm-md5sum_____:
      entryPoints:
        - ep-fm
      rule: "Host(`fm-domain_____`)"
      service: fm-md5sum_____
  services:
    fm-md5sum_____:
      loadBalancer:
        servers:
          - url: http://fm-md5sum_____:7011
